language: generic
dist: bionic
services:
- docker
script:
- make
- rm .gitignore
env:
  matrix:
  - secure: iFGJcz3RGSJFJmljc02pWXYwLGKtCR54IbqAU496qUl2YihAVlt907HUeESls9hHIacHJTOBkdTqd2ekDCDqsghUUt8sJhXNLgsy8kn0qrx0DI1Bhvl2l7ykHrHNGaguNDsEgGuhfuYc6HytX0ySOxmySVijdeUloDabRUHV+EVCpvAZ93AQWeGLapjOvWtih1LCpQ6ajaaz0kdRvGunJB6nnpEm2Ijql1R4lQX2nzhAJ87pbBwwrUxcrqJboj8snCqvP0nCQ08qZLqWYpNF1/wcnPZVl02H3rK2dlFPIsWOgFYmi8p2En1i++bsbjqenpEox+Asz4ywUHfbm4+NUWIj7HZ8mAJUbgkSiri+ln4kAQB8I6eVG7N8tTv+Bhk4qiNd2qr1AdlwneiQIFEuw3f4DrGTtjnFASu4cgP4oX3D42guXqK+ImVnf85xz1CVQCWABu3rF62CEx4rBjsn/PUANHQp0+oDJcxdbA8CfluKABnNUS5dYpE5KedB33mdUXEuShjM9HEhaHXK/gnPEjwaQRR0OvsKPiKBIa4COqpiNZgzy0A5qGVmFoyI88Z1oj9nakwSGzR728tjTKtLZDy1FdXec41SVxrZEvQ2RfafHF9Rx8nC78W9WqfH7AoNKwfpZBGaLpQtox7oUeWco6avKz53dmUx968BEctRzFg=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  target_branch: gh-pages
